config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/projects' => "projects#index", :as => :user_root
  get '/projects/:project_id/tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :task_mark_as_done
  patch '/projects/:project_id/tasks/:id', to: 'tasks#update', as: :task_update
  get '/projects/:project_id/tasks/new', to: 'tasks#new', as: :task_form
  delete '/projects/:project_id/tasks/:id', to: 'tasks#destroy', as: :task_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assignments, only: :create
  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:show, :create, :index]
  end
  resources :users, only: [:index, :show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end


  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to: 'application#server_error'
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :assignments
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one :chatroom, dependent: :destroy

  include PgSearch::Model
  multisearchable against: :title
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project

  def index
    @tasks = Task.includes(:chatroom)
    @tasks = policy_scope(Task).order(created_at: :desc)
    @markers = @tasks.geocoded.map do |task|
      {
        project_id: @project.id,
        task_project_id: task.project.id,
        task_id: task.id,
        lat: task.latitude,
        lng: task.longitude,
        info_window: render_to_string(partial: "info_window", locals: { task: task })
      }
    end
  end

  def show
    @task = Task.find(params[:id]) #check future route
    @task.description

    respond_to do |format|
      format.html { render partial: 'show.html', locals: { project: @project, task: @task } }
      format.text { render partial: 'show.html', locals: { project: @project, task: @task } }
    end
  end

  def new
    @task = Task.new
    authorize @task

    respond_to do |format|
      format.html { render partial: 'create.html', locals: { project: @project } }
      format.text { render partial: 'create.html', locals: { project: @project } }
    end
  end

  def create
    @task = Task.new(task_params)
    @task.project = @project
    @task.status = false
    @chatroom = Chatroom.new(chatroom: @task.title)
    @chatroom.save
    @employees = User.all.select { |user| user.team == "employee" }
    @idle = @employees.min_by { |user| user.assignments.count }
    @assignment = Assignment.new(task_id: @task, user_id: @idle)

    # Take the user that has less assignment
    # when a task is created a new assignment is created between the task and the user that has less tasks

    # if @project.tasks.count != 0
    #   @task.order = @project.tasks.sort_by(&:order).last.order+1
    # else
    #   @task.order = 1
    # end

    authorize @task
    @task.save

    @chatroom = Chatroom.new(chatroom: @task.title, task: @task)
    @chatroom.save

    # @project.tasks.each do |t|
    #   if t != @task && t.order <= @task.order
    #     t.order -= 1
    #     t.save!
    #   end
    # end

    respond_to do |format|
      format.json { redirect_to project_tasks_path(@project) }
      format.html { redirect_to project_tasks_path(@project) }
      format.text { redirect_to project_tasks_path(@project) }
    end
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @task.status = @task.status ? false : true
    authorize @task
    if @task.save!
      redirect_to project_tasks_path(@project)
    else
      render :show
    end
  end

  def update
    @task = Task.find(params[:id])
    @beforetitle = @task.title
    authorize @task
    if current_user.team == 'manager'
      @task.update(manager_task_params)
    else
      @task.update(employee_task_params)
    end
    if @task.status == false || @beforetitle != @task.title
      redirect_to project_tasks_path(@project)
    end
  end

  def complete
    @task = Task.find(params[:id])
    authorize @task
    @task.status = false
    @task.save
    redirect_to project_tasks_path(@project)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    authorize @task
    redirect_to project_tasks_path(@project)
  end

  private

  def manager_task_params
    params.require(:task).permit(:description, :title, :address, :status)
  end

  def employee_task_params
    params.require(:task).permit(:status)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:description, :title, :address)
  end
end

app/views/tasks/_create.html.erb
<div class="whitebck" >

  <div data-controller="create-task" data-project-id=<%=@project.id%> data-user-id=<%=current_user.id%>>
    <%= simple_form_for([@project, @task], remote: true, data: { target: "create-task.form" }) do |f| %>
      <%= f.input :title, label: false, placeholder: "Title", class:"create-task-input form-inline" %>
      <%= f.input :address,label: false, placeholder: "Address", class:"create-task-input form-inline" %>
      <%= f.input :description,label: false, placeholder: "Description", data: {create_task_target:'create-task.description'}, class:"create-task-input form-inline" %>
      <%= f.button :submit, "Create new task", data: { action: "click->create-task#newtask", create_task_target:"buttoncreate" }, class:"create-new-task" %>
    <% end %>
  </div>
 </div>

app/views/tasks/_employee_index.html.erb
<!-- Container -->
<div class="container" data-controller="index create-task" data-project-id=<%=@project.id%>>
  <div class="row">
    <!-- Column 1: Task list card -->
    <div class="col-sm-4">
      <% @project.tasks.each do |task| %>
          <% if task.assignment_ids == current_user.assignment_ids %>
            <%= link_to project_task_path(@project, task), class: "card-product" do %>
              <div class="card-product">
                <div class="card-product-infos">
                  <h2><%=task.title%></h2>
                </div>
              </div>
            <% end %>
          <%end%>
      <%end%>
    </div>
  </div>
</div>

app/views/tasks/_info_window.html.erb
<h2><%= task.title %></h2>

app/views/tasks/_manager_index.html.erb
<!-- Container -->
<div class="container" data-controller="index create-task chat"  data-project-id=<%=@project.id%>>
  <div class="row">
    <!-- Column 1: Task list card -->
    <div class="col-sm-4 p-0">
      <div id="tasks">
        <% @project.tasks.each do |task| %>
          <div class="card-product <%= task.status ? 'bg-green' : 'bg-blue' %>" data-action="click->index#opendescription click->chat#openchat" data-task-id=<%=task.id%> data-chat-id=<%=task.chatroom.id%>>
            <div class="card-product-infos">
              <h2><%=task.title%></h2>
            </div>
          </div>
        <%end%>
      </div>
        <!-- Create new Task buttons (2) -->
      <a class="btn btn-flat" data-action="click->index#newtaskform">Create New Task</a>
    </div>
    <!-- Column 2: Task description -->
    <div class="col-sm-4">
      <div data-index-target="taskdescription">
      </div>
    </div>
    <!-- Column 3: Geocoder -->
    <div class="col-sm-4">
      <div class="mapbox">
        <div id="map"
          style="width: 100%; height: 300px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
     <!-- Column 3: Chatroom -->
      <div id="chat" data-chat-target="chatbox">
      </div>
    </div>
  </div>
</div>

app/views/tasks/_show.html.erb
<% if current_user.team == "manager" %>
  <div class="whitebck todo-box" >
    <h1 class="todo-title">To Do's</h1>
    <div class="adress_form" data-controller="update-task" data-project-id=<%=@project.id%> data-task-id=<%=@task.id%>>
      <%= simple_form_for([@project, @task], remote: true, data: {target: "update-task.form", id: @task.id }) do |f| %>
        <%= f.input :title, label: 'Title', input_html: { data: { action: "input->update-task#editmode", target: 'update.title'}, rows: 9 }, required: true  %>
        <%= f.input :address, label: 'Address', input_html: { data: { action: "input->update-task#editmode", target: 'update.address'}, rows: 9 }  %>
        <%= f.input :description, label: 'To do', input_html: { data: { action: "input->update-task#editmode", target: 'update.description'}, rows: 9 } %>
        <%= link_to 'Delete', task_delete_path(@project, @task), data: { confirm: 'Are you sure you want to delete this task?' }, :method => :delete, class:"btn btn-delete" %>
        <%= f.button :submit, "Save", data: { action: "click->update-task#edit input->update-task#editmode", update_task_target:"button" }, class:"btn btn-save", style:"color:white" %>
      <% end %>
      <div data-target="update.display_description"></div>
    </div>
  </div>
<% else %>
  <div class="whitebck todo-box">
    <h1><%= task.title %></h1>
    <div>
        <p class="address"><%= task.address %></p>
        </br>
        <p><%= task.description %></p>
      <%= link_to 'Done!', task_mark_as_done_path(@project, @task), class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="project-title"><%=@project.title%></h1>
  <%= render "manager_index" %>
</div>

app/views/tasks/task_description.html.erb
<div class="task-card" data-controller="edit-task" data-edit-task-target="card">