config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/projects' => "projects#index", :as => :user_root
  get '/projects/:project_id/tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :task_mark_as_done
  patch '/projects/:project_id/tasks/:id', to: 'tasks#update', as: :task_update
  get '/projects/:project_id/tasks/new', to: 'tasks#new', as: :task_form
  delete '/projects/:project_id/tasks/:id', to: 'tasks#destroy', as: :task_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assignments, only: :create
  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:show, :create, :index]
  end
  resources :users, only: [:index, :show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end


  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to: 'application#server_error'
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :assignments
  has_many :projects

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: %I[first_name last_name],
                  using: {
                    tsearch: { prefix: true }
                  }
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: :index

  def index
    if params[:user_query].present?
      @users = policy_scope(User).search_by_name(params[:user_query])
      @tasks = policy_scope(Task).order(created_at: :desc)
    elsif params[:task_query].present?
      @tasks = policy_scope(Task).search_by_title(params[:task_query])
      @users = policy_scope(Task).order(created_at: :desc)
    else
      @users = policy_scope(User).order(created_at: :desc)
      @tasks = policy_scope(Task).order(created_at: :desc)
    end
    @assignment = Assignment.new
  end

  def show
    @user = User.find(params[:id]) #check future route
    @user.first_name
    @user.last_name

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'show.html', locals: { user: @user } }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end
  #def new
  #  @user = user.new
  #  authorize @user

  #  respond_to do |format|
  #    format.html { render partial: 'create.html', locals: { project: @project } }
  #    format.text { render partial: 'create.html', locals: { project: @project } }
  #  end
  # end

  # def create
  #  @user = user.new(user_params)
  #  @user.project = @project
  #  @user.status = false
  #  # if @project.users.count != 0
  #  #   @user.order = @project.users.sort_by(&:order).last.order+1
  #  # else
  #  #   @user.order = 1
  #  # end

  #  authorize @user

  #  # @project.users.each do |t|
  #  #   if t != @user && t.order <= @user.order
  #  #     t.order -= 1
  #  #     t.save!
  #  #   end
  #  # end
  # @user.save

  #  respond_to do |format|
  #    format.json { redirect_to project_users_path(@project) }
  #    format.html { redirect_to project_users_path(@project) }
  #    format.text { redirect_to project_users_path(@project) }
  #  end
  # end

  # def complete!
  #   @user = user.find(params[:id])
  #   @user.status = true
  #   @user.save!
  # end

  # def update
  #   @user = user.find(params[:id])
  #   authorize @user
  #   @user.update(user_params)
  # end

# def destroy
#   @user.destroy
#   authorize @trask
#   redirect_to project_user_path
# end

# private

# def set_project
#   @project = Project.find(params[:project_id])
# end

# def user_params
# params.require(:user).permit(:description, :title, :address)
#   end

app/views/users/_show.html.erb
<div>
  <h3 class="user-name"> <strong> Name: </strong> <%= @user.full_name %> <strong>Email: </strong><%= @user.email  %></h3>
</div>
<div class="d-flex">
  <% @user.assignments.each do |assignment| %>
    <div class="assignment-cards">
     <%= link_to assignment.task.title, project_tasks_path(assignment.task.project) %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div>
    <h1 class="project-title">Users</h1>
  </div>

  <!-- Container -->
  <div data-controller="index">
    <div class="row">
      <!-- Column 1: user list card -->
      <div class="col-sm-4">
        <%= form_tag users_path, method: :get do %>
          <div id="search-bar" class="my-5 input-group">
            <%= text_field_tag :user_query,
              params[:user_query],
              class: "form-control",
              placeholder: "Find a user"
            %>
            <%= submit_tag "Find", class: "btn btn-secondary" %>
          </div>
        <% end %>
        <% @users.each do |user| %>
          <% if user.team == "employee" %>
            <div class="card-product-employee" data-action="click->index#openUser" data-user-id=<%=user.id%>>
              <div class="card-product-infos">
                <h2><%=user.first_name%> <%= user.last_name %></h2>
                <%= link_to '#', class: 'btn btn-success' do %>
                  <i class='fas fa-check'></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <%end%>
      </div>

      <div class="col-sm-8 user-show">
        <div data-index-target="userdescription"></div>
      </div>
    </div>
  </div>
</div>