config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/projects' => "projects#index", :as => :user_root
  get '/projects/:project_id/tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :task_mark_as_done
  patch '/projects/:project_id/tasks/:id', to: 'tasks#update', as: :task_update
  get '/projects/:project_id/tasks/new', to: 'tasks#new', as: :task_form
  delete '/projects/:project_id/tasks/:id', to: 'tasks#destroy', as: :task_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assignments, only: :create
  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:show, :create, :index]
  end
  resources :users, only: [:index, :show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end


  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to: 'application#server_error'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!---Navbar --->

<section class="mb-5">

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= current_user && params[:action] != "home" ? "dark-background" : "light-background"%>">
    <%= link_to root_path, class: "navbar-brand" do %>
      <% if  current_user && params[:action] != "home" %>
        <%= image_tag "LogoWhite.png" %>
      <% else %>
        <%= image_tag "LogoTemplate.png" %>
      <% end %>
    <% end %>

    <div class="d-flex navbar-links <%= current_user && params[:action] != "home" ? "light-color" : "dark-color"%>">
      <%= "|" %>
      <% if params[:action] == "home"%>
        <%= link_to "How it works", root_path(anchor: "how-it-works") %>

      <% end %>
        <%= link_to "Users", users_path(anchor: "Users") %>
        <%= link_to "Projects", projects_path %>
    </div>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#", class: "nav-link-signed-in #{current_user && params[:action] != "home" ? "light-color" : "dark-color"}" do %>
              <i class="fas fa-bell"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn sign-out" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item btn home-login">
            <%= link_to "Login", new_user_session_path, class: "nav-link-logged-out" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</section>