config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/projects' => "projects#index", :as => :user_root
  get '/projects/:project_id/tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :task_mark_as_done
  patch '/projects/:project_id/tasks/:id', to: 'tasks#update', as: :task_update
  get '/projects/:project_id/tasks/new', to: 'tasks#new', as: :task_form
  delete '/projects/:project_id/tasks/:id', to: 'tasks#destroy', as: :task_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assignments, only: :create
  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:show, :create, :index]
  end
  resources :users, only: [:index, :show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end


  if Rails.env.production?
    get '404', to: 'application#page_not_found'
    get '422', to: 'application#server_error'
    get '500', to: 'application#server_error'
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title,
                  against: :title,
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :update, :destroy]

  def index
    if params[:query].present?
      @projects = policy_scope(Project).search_by_title(params[:query])
    else
      @projects = policy_scope(Project).order(created_at: :desc)
    end
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @user = current_user
    @project.user = @user
    authorize @project
    @project.save
    redirect_to projects_path
  end

  def update
    @project.update(project_params)
    respond_to do |format|
      authorize @project
      if @project.save
        format.html { redirect_to projects_path(@project) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render 'projects/show' }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  def destroy
    @project.destroy
    authorize @project
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/views/projects/_create_form.html.erb
<%= simple_form_for @project, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
  <%= f.input :title, label: "false", placeholder: "Name of the project", class:"create-project-input form-inline" %>
  <%= f.button :submit, "Create new project", class:"create-project"%>
<% end %>

app/views/projects/_edit_form.html.erb
<% if false %>
  <%= simple_form_for(project,
                      data: {
                        project_id: project.id,
                        project_card_target: "form inputTarget",
                        action: "submit->project-card#saveCard"
                      }) do |f| %>
    <%= f.input :title, label: false, value: project.title, wrapper_html: { data: { project_card_target: "titleInput" } } %>
    <%= button_tag(type: 'submit', class: "fas fa-save",
                    data: {
                      # action: "click->project-card#submitSaveForm"
                    }) do %>
      <i></i>
    <% end %>
  <% end %>
<% end %>


<div class="edit_form" data-controller="new_edit">
  <%= simple_form_for(project, remote: true,data: {target: "new_edit.form", id: project.id }) do |f| %>
    <%= f.input :title, label: false, input_html: { data: {target: 'new_edit.title'} }, required: true  %>
    <%= button_tag(type: 'submit', class: "fas fa-save",
                  data: {
                    action: "click->new_edit#refresh" }) do %>
                      <i></i>
                    <% end %>
  <% end %>
  <div data-target="new_edit.display_title"></div>
</div>




 <%#=  // app/javascript/controllers/projects_controller.js

import { Controller } from "stimulus";
import { fetchWithToken } from "../utils/fetch_with_token";

export default class extends Controller {
	static targets = ["form", "line1", "display_address"]

  refresh() {
  	let id = event.target.form.dataset.id;
	  fetchWithToken(`/me/${id}`, {
	    method: "PATCH",
	    headers: {
	      "Accept": "application/json",
	      "Content-Type": "application/json"
	    },
	    body: JSON.stringify({
	    	user: {
	    		line1: this.line1
	    	}
	    })
	  }).then(response => response.json())
	    .then((data) => {
	      console.log(data)
	    });

  	if (this.line1 != "") {
    	this.display_addressTarget.innerText = `Mon adresse actuelle : ${this.line1}`;
    }
  }

  get line1 () {
  	return this.line1Target.value
  }
}


// app/javascript/utils/fetch_with_token.js

import { csrfToken } from "@rails/ujs";

const fetchWithToken = (url, options) => {
  options.headers = {
    "X-CSRF-Token": csrfToken()
  };

  return fetch(url, options);
}

export { fetchWithToken };
%>

app/views/projects/index.html.erb
<!-- TITLE AND CREATE FORM -->
<div class="container p-0">
  <div class="row justify-content-between">
    <h1 class="project-title">Projects</h1>
    <%= render "create_form" %>
  </div>
  <!-- SEARCH FORM -->
  <%= form_tag projects_path, method: :get do %>
  <div id="search-bar" class="my-5 input-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a project"
    %>
    <%= submit_tag "Search", class: "btn btn-secondary" %>
  </div>
  <% end %>
  <!-- CARDS -->
  <div class="cards">
    <% @projects.each do |project|%>
        <div class="card-category-yellow" data-controller="project-card">
          <div data-project-card-target="view" class="js-project-view">
            <h3 data-project-card-target="projectTitle"><%= link_to project.title, project_tasks_url(project), :class => "pt" %></h3>
            <div class="d-flex justify-content-between">
              <p><%= pluralize project.tasks.length, "task" %></p>
              <div class="links">
                <i class="fas fa-pencil-alt" data-action="click->project-card#preventDefault click->project-card#editCard"></i>
                <%= link_to project, method: :delete, remote: true do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
          </div>
          <div data-project-card-target="edit" class="js-project-edit">
            <%= render "edit_form", project: project %>
            <div class="d-flex justify-content-between">
              <p><%= pluralize project.tasks.length, "task" %></p>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>